name = "Keo Optimized"
author = "Jofree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7776c0aa5ac5b9988f2094edcfe18fea505f7a4e06c7d16b0d0e21297468c0ed"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
