name = "Keo Optimized"
author = "Jofree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50c1a2f99db746474635c736f54c261c534576daf17df03d1be623a4325b4651"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
