name = "Keo Optimized"
author = "Jofree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c95a98e2df2e6aa45367f1a3df493557536f00619976c700389c39cdf1fbb0da"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
