[button]
enabled = true
showBadge = true
relativeToInventory = true
x = 52
y = -26
badgeX = 24
badgeY = 0
bobbingBadge = true
[gui]
mainPanelX = 0
mainPanelY = 0
searchBarX = 0
searchBarY = 0
chapterButtonsX = 0
chapterButtonsY = 0
[colors]
textColor = 4995099
titleColor = 4995099
completedTextColor = 5414482
failedTextColor = 11141120
uncollectedTextColor = 10380850
progressTextColor = 10385490
hoveredTextColor = 16777215
searchTextColor = 4995099
noQuestsColor = 4995099
hoverFillColor = -2130706433
toastTitleColor = 10380850
toastDescriptionColor = 4995099
